# Generated by Django 5.1.5 on 2025-01-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cash", models.FloatField()),
                ("total_inventory", models.FloatField()),
                ("non_current_asset", models.FloatField()),
                ("current_liability", models.FloatField()),
                ("gross_profit", models.FloatField()),
                ("retained_earnings", models.FloatField()),
                ("earnings_before_interest", models.FloatField()),
                ("dividends_per_share", models.FloatField()),
                ("total_stockholders_equity", models.FloatField()),
                ("total_market_value", models.FloatField()),
                ("total_revenue", models.FloatField()),
                ("net_cash_flow", models.FloatField()),
                ("total_long_term_debt", models.FloatField()),
                ("total_interest_and_related_expense", models.FloatField()),
                ("sales_turnover_net", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_rating", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_input",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="risk_model.userinput",
                    ),
                ),
            ],
        ),
    ]
