# Generated by Django 5.1.5 on 2025-02-07 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('revenue', models.FloatField()),
                ('risk_category', models.CharField(choices=[('Low Risk', 'Low Risk'), ('Medium Risk', 'Medium Risk'), ('High Risk', 'High Risk')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=6)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Default', 'Default')], default='Default', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField()),
                ('total_inventory', models.FloatField()),
                ('non_current_asset', models.FloatField()),
                ('current_liability', models.FloatField()),
                ('gross_profit', models.FloatField()),
                ('retained_earnings', models.FloatField()),
                ('earnings_before_interest', models.FloatField()),
                ('dividends_per_share', models.FloatField()),
                ('total_stockholders_equity', models.FloatField()),
                ('total_market_value', models.FloatField()),
                ('total_revenue', models.FloatField()),
                ('net_cash_flow', models.FloatField()),
                ('total_long_term_debt', models.FloatField()),
                ('total_interest_and_related_expense', models.FloatField()),
                ('sales_turnover_net', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inputs', to='risk_model.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_rating', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='risk_model.userinput')),
            ],
        ),
    ]
