# Generated by Django 5.1.5 on 2025-01-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_model", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("revenue", models.FloatField()),
                (
                    "risk_category",
                    models.CharField(
                        choices=[
                            ("Low Risk", "Low Risk"),
                            ("Medium Risk", "Medium Risk"),
                            ("High Risk", "High Risk"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
