# Generated by Django 5.1.5 on 2025-02-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_model", "0002_alter_userinput_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinput",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
